
datasource:

  openmrs:
    url: jdbc:mysql://localhost:3306/openmrs_neno?autoReconnect=true&sessionVariables=storage_engine=InnoDB&useUnicode=true&characterEncoding=UTF-8
    user: root
    password: root

  analysis:
    url: jdbc:mysql://localhost:3306/reporting_test?autoReconnect=true&sessionVariables=storage_engine=InnoDB&useUnicode=true&characterEncoding=UTF-8
    user: root
    password: root

