
logging:
  file:
    name: "${PETL_HOME}/logs/petl.log"
  level:
    root: "WARN"
    org.pih: "INFO"

spring:
  datasource:
    platform: "h2"
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:file:${PETL_HOME}/data/petl;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE"
    username: "sa"
    password: "Test123"
    data: "classpath:schema-h2.sql"
  jpa:
    hibernate:
      ddl-auto: "none"
  quartz:
    job-store-type: "memory"
