
targetEnvironment:
  databaseConnection:
    connectionName: "Warehouse"
    hostname: "localhost"
    port: 3308
    databaseName: "pentaho_neno"
    username: "root"
    password: "root"

sourceEnvironments:
  - name: "Neno"
    country: "malawi"
    databaseConnection:
        connectionName: "OpenMRS"
        hostname: "localhost"
        port: 3308
        databaseName: "openmrs"
        username: "root"
        password: "root"
    keyPrefix: "100"
