
logging:
  file:
    name: "/home/mseaton/environments/petl/logs/petl.log"
  level:
    root: "WARN"
    org.pih: "DEBUG"

startupJobs:
  exitAutomatically: "true"
  jobs:
    - "/job1.properties"
    - "/job2.properties"
